name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * 1"
env:
  DOCKERFILE_PATH: Dockerfile  # Make Dockerfile path configurable
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get latest version code
        id: generate_versionno
        run: |-
          curl -fsSL "https://api.github.com/repos/r3-team/r3/tags" | jq -r '.[0].name | sub("v";"ver=";"i")' >> $GITHUB_OUTPUT

      - name: Build and Push ARM64 Docker Image
        uses: docker/build-push-action@v6.17.0
        with:
          context: .
          platforms: linux/arm64
          build-args: |
            r3_version=${{ steps.generate_versionno.outputs.ver }}
            r3_db_host=r3-db
            r3_db_name=app
            r3_db_user=app
            r3_db_pass=app
            r3_os_arch=arm64
            im_policy=/etc/ImageMagick-6/policy.xml
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.generate_versionno.outputs.ver }}-arm64


      - name: Build and Push AMD64 Docker Image
        uses: docker/build-push-action@v6.17.0
        with:
          context: .
          platforms: linux/amd64
          build-args: |
            r3_version=${{ steps.generate_versionno.outputs.ver }}
            r3_db_host=r3-db
            r3_db_name=app
            r3_db_user=app
            r3_db_pass=app
            r3_os_arch=x64
            im_policy=/etc/ImageMagick-6/policy.xml
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.generate_versionno.outputs.ver }}-amd64
